# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'image_converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_from = QtWidgets.QLabel(MainWindow)
        self.label_from.setObjectName("label_from")
        self.verticalLayout.addWidget(self.label_from)
        self.comboBox_from = QtWidgets.QComboBox(MainWindow)
        self.comboBox_from.setObjectName("comboBox_from")
        self.verticalLayout.addWidget(self.comboBox_from)
        self.label_to = QtWidgets.QLabel(MainWindow)
        self.label_to.setObjectName("label_to")
        self.verticalLayout.addWidget(self.label_to)
        self.comboBox_to = QtWidgets.QComboBox(MainWindow)
        self.comboBox_to.setObjectName("comboBox_to")
        self.verticalLayout.addWidget(self.comboBox_to)
        self.pushButton_select = QtWidgets.QPushButton(MainWindow)
        self.pushButton_select.setObjectName("pushButton_select")
        self.verticalLayout.addWidget(self.pushButton_select)
        self.pushButton_convert = QtWidgets.QPushButton(MainWindow)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.verticalLayout.addWidget(self.pushButton_convert)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Format Converter"))
        self.label_from.setText(_translate("MainWindow", "Convert From:"))
        self.label_to.setText(_translate("MainWindow", "Convert To:"))
        self.pushButton_select.setText(_translate("MainWindow", "Select Images"))
        self.pushButton_convert.setText(_translate("MainWindow", "Convert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
